# no time!
alias A='alias'
alias AG='A | G'
alias C='bat -p'
alias G='rg'
alias GV='rg -v'
alias L='command less'
alias PG="command ps -auxww | G"
alias PGW="command watch pgrep -a"
alias S='command sort'
alias T='command tail -f'

# general
alias bc='command bc -l -q'
alias cat='bat -p'
alias cdh='eval cd ~$USER'
alias cert.info='command openssl x509 -text -noout -in'
if [ -z "${SUDO_UID}" ] && [ -z "${SUDO_GUID}" ]; then
  alias chown.me='command sudo chown $(id -u):$(id -g)'
else
  shellcheck disable=SC2153
  alias chown.me='command sudo chown ${SUDO_UID}:${SUDO_GID}'
fi
alias chown.root='command sudo chown root:root'
alias chromecast='command go-chromecast -d Chromecast'
alias curlh='command curl -s -o /dev/null -D -'
alias curlhs='command curl -s -o /dev/null -D - --proto-default https'
alias curls='command curl -s'
alias df.real='command df -x squashfs -x tmpfs -x devtmpfs'
alias dfch='command dfc -TW -t -squashfs,tmpfs,devtmpfs'
alias dfh='command df -h -x squashfs -x tmpfs -x devtmpfs'
alias diff='command diff --color=auto'
alias dig.auth='command dig +trace'
alias dig.cloudflare='command dig @1.1.1.1'
alias dig.google='command dig @8.8.8.8'
alias dig.quad9='command dig @9.9.9.9'
alias dig.systemd='command resolvectl query'
alias digs.cloudflare='command dig +short @1.1.1.1'
alias digs.google='command dig +short @8.8.8.8'
alias digs.quad9='command dig +short @9.9.9.9'
alias digs='command dig +short'
alias digx='command dig +short -x'
alias dmesgf='command sudo dmesg -wH'
alias fda='command fd --absolute-path'
alias fdh='command fd --hidden'
alias fdhh='fd --hidden --no-ignore --full-path'
alias ft='export TERM=xterm-256color'
alias iftop='LANG=C command iftop'
alias intro='clear && echo "pimp\n    my\n        shell" | figlet | lolcat -a -t -s 30'
alias ip6tablesl='sudo ip6tables -L -v -n'
alias ip6tableslnat='sudo ip6tables -t nat -L -v -n | less'
alias ip='command ip -c'
alias ipa='ip addr'
alias ipad='ip addr show dev'
alias ipbr='ip -br addr'
alias ipd='ip addr show dev'
alias ipr='ip route'
alias iptablesl='command sudo command iptables -L -v -n | L'
alias iptableslnat='command sudo command iptables -t nat -L -v -n | L'
alias irssi='TERM=screen-256color command irssi'
alias jq='jq.less'
alias jqr='command jq -r'
alias lock='command swaylock -f -C ~/.config/sway-lock/config; command systemctl suspend'
alias lsb='command hostnamectl'
alias lsba='command lsb_release -a'
alias miset='command mise task run'
alias mount.real='command mount | command grep --color=never -e "^/dev"'
alias mpva='command mpv --no-audio-display --vo=null --save-position-on-quit --resume-playback'
alias mute='command pulsemixer --mute'
alias ncdu='command ncdu --color dark'
alias newpw='command pwgen -sB 42 1 | command tr -d "\n"'
alias nonet='command unshare -U -n'
alias please='command sudo'
alias plm.tmux='command tmux source "${HOME}/.tmux-fkeys-disable.conf" && command pulsemixer && command tmux source "${HOME}/.tmux-fkeys.conf"'
alias plm='command pulsemixer'
alias pping='command prettyping'
alias psitop='command watch -n 1.5 -d command head /proc/pressure/*'
alias psitops='command watch -t -n 1.5 -d "command head /proc/pressure/* | command sed \"s/total=.*$//g\""'
alias psz='ps haxo pid:1,stat:1 | grep Z | cut -d" " -f1 | xargs -r ps o user:24,pid,pcpu,pmem,vsz,rss,tty,stat,lstart,time,command -p | L'
alias pszz='ps haxo ppid:1,stat:1 | grep Z | cut -d" " -f1 | xargs -r ps o user:24,pid,pcpu,pmem,vsz,rss,tty,stat,lstart,time,command -p | L'
alias pwdxc='command pwd | xc --trim'
alias r='source "${HOME}/.zshrc.local"'
alias rg='command rg --smart-case --sort path --colors "match:bg:yellow" --colors "match:fg:black" --colors "match:style:nobold" --colors "path:fg:green" --colors "path:style:bold" --colors "line:fg:yellow" --colors "line:style:bold"'
alias rgh='rg --hidden'
alias rt='export TERM=${TERM}'
alias sftpi='command sftp -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null"'
alias sofkans="sofka -n \$(kubectl config view --minify --output 'jsonpath={..namespace}')"
alias ss.listen='command ss -tulpn | command column | command less'
alias ss.listenv='command ss -tulpen | command column | command less'
alias ssh='ssht'
alias sshc='/usr/bin/ssh'
alias sshi='command ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null"'
alias sudoe='command sudo -s -E'
alias sudoi='command sudo -i'
alias sudoiu='command sudo -i -u'
alias sudou='command sudo -u'
alias t.brief='command trans --brief'
alias t.de='command trans en:de'
alias t.en='command trans de:en'
alias tmuxa='command tmux a -t'
alias ubuntu='command sudo systemd-nspawn --boot --directory=/mnt/ubuntu'
alias unmute='command pulsemixer --unmute'
alias vd='command nvim -d'
alias vi='command nvim -p'
alias vialiases='${EDITOR} "${HOME}/.zsh/aliases.zsh"'
alias view='command nvim -R'
alias vim='command nvim -p'
alias vimdiff='command nvim -d'
alias vip='command nvim -p'
alias vissh='${EDITOR} "${HOME}/.ssh/config"'
alias watch='command watch -c '
alias whereami='echo $(command curl -s6 ifconfig.co/json; command curl -s4 ifconfig.co/json) | jq "del(.user_agent, .ip_decimal)"'
alias wlr='systemctl --user restart wl-paste.service'
alias wttr='command curl https://wttr.in/Augsburg'
if [[ "${XDG_SESSION_TYPE}" == 'wayland' ]]; then
  alias xc='command wl-copy'
  alias xp='command wl-paste'
elif [[ "${XDG_SESSION_TYPE}" == 'x11' ]]; then
  alias xc='command xsel -i -b'
  alias xp='command xsel -o -b'
fi
alias yt='command ytfzf'

# chezmoi
alias cz='command chezmoi'
alias cza='command chezmoi add'
alias czcd='command chezmoi cd'
alias czd='command chezmoi diff'
alias czdata='command chezmoi data | jq'
alias czdr='command chezmoi diff --reverse'
alias cze='command chezmoi edit'
alias czst='command chezmoi status'

# git
alias gbD-='command git branch -D @{-1}'
alias gbc='command git branch --contains=HEAD | cut -d" " -f2- | sed -z "$ s/\n$//" | xc'
alias gbd-='command git branch -d @{-1}'
alias gc-='command git checkout -'
alias gcpp='command git cherry-pick'
alias gdcan='GIT_PAGER="delta --features=no-line-numbers" gdca'
alias gdn='GIT_PAGER="delta --features=no-line-numbers" gd'
alias glc='command git log -1 --format=%s | sed -z "$ s/\n$//" | xc'
alias glod='command git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%aN>%Creset"'
alias glods='command git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%aN>%Creset" --date=short'
alias glol='command git log --graph --pretty="%C(yellow)%h %C(cyan)%G?%Creset %s%C(auto)%d%Creset %Cgreen(%cr) %C(bold blue)<%an>%Creset %GK"'
alias glola='command git log --graph --pretty="%C(yellow)%h %C(cyan)%G?%Creset %s%C(auto)%d%Creset %Cgreen(%cr) %C(bold blue)<%an>%Creset %GK" --all'
alias glolm='gstm | fzf | xargs git log --graph --pretty="%C(yellow)%h %C(cyan)%G?%Creset %s%C(auto)%d%Creset %Cgreen(%cr) %C(bold blue)<%aN>%Creset %GK"'
alias glols='command git log --graph --pretty="%C(yellow)%h %C(cyan)%G?%Creset %s%C(auto)%d%Creset %Cgreen(%cr) %C(bold blue)<%an>%Creset %GK" --stat'
alias glow='command glow -l -p'
alias gm-='command git merge @{-1}'
alias gshn='GIT_PAGER="delta --features=no-line-numbers" gsh'
alias gsl='command git shortlog'
alias gstm="command git status --short | rg '^ M' | cut -f3- -d' '"

# k8s
alias k9sro='k9s --readonly'
alias k='command kubecolor'
alias kctx='command kubectx'
alias kd='kubectl describe'
alias kdA='kubectl describe -A'
alias ke='kubectl explain'
alias kg='kubectl get'
alias kgA='kubectl get -A'
alias kgcns='kubectl config view --minify -o "jsonpath={..namespace}"'
alias kgdi='kubectl get deployments -o custom-columns="NAMESPACE:.metadata.namespace,NAME:.metadata.name,IMAGE:.spec.template.spec.containers[*].image"'
alias kgpf='kubectl get pods --field-selector "status.phase!=Running,status.phase!=Succeeded"'
alias kgpi='kubectl get pod -o custom-columns="NAMESPACE:.metadata.namespace,NAME:.metadata.name,STATUS:.status.phase,AGE:.metadata.creationTimestamp,IMAGE:.spec.containers[*].image"'
alias kgsecda="kubectl get secrets --field-selector type!=helm.sh/release.v1 -o json | jq '.items[] | { name: .metadata.name, type: .type, data: .data | map_values(@base64d) }'"
alias kns='command kubens'
alias kns-='command kubens -'
alias kubectl='kubecolor'
alias cilium-dbg='kubectl -n kube-system exec -it ds/cilium -- cilium-dbg'
alias fluxlf="flux logs --since 5m -A -f"
alias fluxns="flux -n \$(kubectl config view --minify --output 'jsonpath={..namespace}')"
alias fluxup='command flux reconcile ks flux-system --with-source'

# ls
alias l1='command eza -1'
alias l='command eza -lgB'
alias la='command eza -a'
alias lg='command eza -lga --git --git-ignore'
alias lh='command eza -lg'
alias ll='command eza -lag --git'
alias lla='command eza -lga'
alias lln='command eza -lga -snew'
alias llo='command eza -lga -snew -r'
alias llv='command eza -lh --inode --links --group --time-style=long-iso'
alias ls='command eza'

# opentofu
alias tg='command terragrunt'
alias tga='command terragrunt apply'
alias tgaa='command terragrunt apply -refresh-only'
alias tgarf='command terragrunt apply -refresh=false'
alias tgawd='command terragrunt apply --terragrunt-working-dir'
alias tgfu='command terragrunt force-unlock -force'
alias tgi='command terragrunt init'
alias tgo='command terragrunt output'
alias tgoj='command terragrunt output -json'
alias tgp='command terragrunt plan'
alias tgprf='command terragrunt plan -refresh=false'
alias tgpwd='command terragrunt plan --terragrunt-working-dir'
alias tgr='command terragrunt refresh'
alias tgra='command terragrunt run --all'
alias tgrap='command terragrunt run --all plan | tfsilent'
alias tgrapv='TG_TF_FORWARD_STDOUT=false command terragrunt run --all plan | tfsilent'
alias tgs='command terragrunt show'
alias tf='command tofu'
alias tfa='command tofu apply'
alias tfi='command tofu init'
alias tfo='command tofu output'
alias tfoj='command tofu output -json'
alias tfp='command tofu plan'
alias tfs='command tofu show'
alias tfsilent='command grep -v "Refreshing state...\|Reading...\|Still reading...\|Read complete after\|Reusing previous version\|Using previously-installed\|create plugin cache directory if absent"'

# systemd
alias jc='command journalctl'
alias jcf='command journalctl --follow'
alias jcu='command journalctl --user'
alias jcuf='command journalctl --user --follow'
alias running='command systemctl --state=running'
alias sc-running='command systemctl --state=running'
alias sc='command systemctl'
alias scf='command systemctl --failed'
alias scu-running='command systemctl --user --state=running'
alias scu='command systemctl --user'
alias scuf='command systemctl --user --failed'

# suffix aliases
alias -s crt="command openssl x509 -text -noout -in "
alias -s csr="command openssl req -text -noout -in "
alias -s md="glow"
alias -s pem="command openssl x509 -text -noout -in "
