# no time!
alias A='alias'
alias AG='A | G'
alias B='command bat'
alias C='command cat'
alias G='rg'
alias L='command less'
alias S='command sort'
alias T='command tail -f'

# new
alias jn='command journalctl'
alias jnf='command journalctl --follow'
alias jnu='command journalctl --user'
alias jnuf='command journalctl --user --follow'
alias sc-running='command systemctl --state=running'
alias sc='command systemctl'
alias scu='command systemctl --user'
alias psitop='command watch -n 1.5 -d command head /proc/pressure/*'
alias psitops='command watch -t -n 1.5 -d "command head /proc/pressure/* | command sed \"s/total=.*$//g\""'
alias tmuxa='command tmux a -t'
alias dfh='command df -h -x squashfs -x tmpfs -x devtmpfs'
alias pping='command prettyping'
alias intro='clear && echo "pimp\n    my\n        shell" | figlet | lolcat -a -t -s 30'
alias tg='command terragrunt'
alias tf='command terraform'
alias dmesgf='command sudo dmesg -wH'
alias vissh='${EDITOR} "${HOME}/.ssh/config"'
alias cz='command chezmoi'
alias cza='command chezmoi add'
alias czcd='command chezmoi cd'
alias czd='command chezmoi diff'
alias czdr='command chezmoi diff --reverse'
alias cze='command chezmoi edit'
alias czdata='command chezmoi data | jq'
alias czst='command chezmoi status'
alias cat='command bat -p'
alias miset='command mise task run'

# k8s
alias kubectl='kubecolor'
alias kd='kubectl describe'
alias kdA='kubectl describe -A'
alias kg='kubectl get'
alias kgA='kubectl get -A'
alias ke='kubectl explain'
alias kns='command kubens'
alias kgcns='kubectl config view --minify -o "jsonpath={..namespace}"'
alias kapi='kubectl --force-colors --no-headers=true api-resources | fzf --ansi'
alias cilium-dbg='kubectl -n kube-system exec -it ds/cilium -- cilium-dbg'
alias fluxns='flux -n \$(kgcns)'
alias fluxup='command flux reconcile ks flux-system --with-source'

# aliases
alias bc='command bc -l -q'
alias cdh='eval cd ~$USER'
alias cert.info='command openssl x509 -text -noout -in'
alias chown.me='command sudo chown $(id -u):$(id -g)'
alias chown.root='command sudo chown root:root'
alias chromecast='command go-chromecast -d Chromecast'
alias curl.header='command curl -s -o /dev/null -D -'
alias curl.dl='command curl -O'
alias curls='command curl -s'
alias df.real='command df -x squashfs -x tmpfs -x devtmpfs'
alias diff='command diff --color=auto'
alias dig.auth='command dig +trace'
alias dig.cloudflare='command dig @1.1.1.1'
alias dig.google='command dig @8.8.8.8'
alias dig.quad9='command dig @9.9.9.9'
alias dig.systemd='command resolvectl query'
alias digs.cloudflare='command dig +short @1.1.1.1'
alias digs.google='command dig +short @8.8.8.8'
alias digs.quad9='command dig +short @9.9.9.9'
alias digs='command dig +short'
alias digx='command dig +short -x'
alias fda='command fd --absolute-path'
alias fdh='command fd --hidden'
alias ft='export TERM=xterm-256color'
alias gbD-='command git branch -D @{-1}'
alias gbd-='command git branch -d @{-1}'
alias gc-='command git checkout -'
alias glol='command git log --graph --pretty="%C(yellow)%h %C(cyan)%G?%Creset %s%C(auto)%d%Creset %Cgreen(%cr) %C(bold blue)<%an>%Creset %GK"'
alias glola='command git log --graph --pretty="%C(yellow)%h %C(cyan)%G?%Creset %s%C(auto)%d%Creset %Cgreen(%cr) %C(bold blue)<%an>%Creset %GK" --all'
alias glols='command git log --graph --pretty="%C(yellow)%h %C(cyan)%G?%Creset %s%C(auto)%d%Creset %Cgreen(%cr) %C(bold blue)<%an>%Creset %GK" --stat'
alias glow='command glow -l -p'
alias gm-='command git merge @{-1}'
alias gsl='command git shortlog'
alias ip='command ip -c'
alias ipa='ip addr'
alias ipad='ip addr show dev'
alias ipbr='ip -br addr'
alias irssi='TERM=screen-256color command irssi'
alias jq='jq.less'
alias l1='command eza -1'
alias l='command eza -lgB'
alias la='command eza -a'
alias lg='command eza -lga --git --git-ignore'
alias lh='command eza -lg'
alias ll='command eza -lag'
alias lla='command eza -lga'
alias lln='command eza -lga -snew'
alias llo='command eza -lga -snew -r'
alias llv='command eza -lh --inode --links --group --time-style=long-iso'
alias lock='command swaylock -f -C ~/.config/sway-lock/config; command systemctl suspend'
alias ls='command exa'
alias lsb='command hostnamectl'
alias mount.real='command mount | command grep --color=never -e "^/dev"'
alias mpva='command mpv --no-audio-display --vo=null --save-position-on-quit --resume-playback'
alias mute='command pulsemixer --mute'
alias ncdu='command ncdu --color dark'
alias nonet='command unshare -U -n'
alias plm.tmux='command tmux source "${HOME}/.tmux-fkeys-disable.conf" && command pulsemixer && command tmux source "${HOME}/.tmux-fkeys.conf"'
alias plm='command pulsemixer'
alias r='source "${HOME}/.zshrc.local"'
alias rg='command rg --colors "match:bg:yellow" --colors "match:fg:black" --colors "match:style:nobold" --colors "path:fg:green" --colors "path:style:bold" --colors "line:fg:yellow" --colors "line:style:bold"'
alias rgh='rg --hidden'
alias rt='export TERM=${TERM}'
alias sftpi='command sftp -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null"'
alias ss.listen='command ss -tulpn | command column | command less'
alias ss.listenv='command ss -tulpen | command column | command less'
alias ssh='ssht'
alias sshi='command ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null"'
alias sudoe='command sudo -s -E'
alias sudoi='command sudo -i'
alias sudoiu='command sudo -i -u'
alias sudou='command sudo -u'
#alias tf='command tail -f'
alias trans.brief='command trans --brief'
alias trans.de='command trans en:de'
alias trans.en='command trans de:en'
alias tw='command timew'
alias ubuntu='command sudo systemd-nspawn --boot --directory=/mnt/ubuntu'
alias unmute='command pulsemixer --unmute'
alias vd='command nvim -d'
alias vi='command nvim'
alias view='command nvim -R'
alias vim='command nvim'
alias vimdiff='command nvim -d'
alias vip='command nvim -p'
alias watch='command watch -c '
alias whereami='echo $(command curl -s6 ifconfig.co/json; command curl -s4 ifconfig.co/json) | jq "del(.user_agent, .ip_decimal)"'
alias yt='command ytfzf'
if [[ "${XDG_SESSION_TYPE}" == 'wayland' ]]; then
  alias xc='command wl-copy'
  alias xp='command wl-paste'
elif [[ "${XDG_SESSION_TYPE}" == '11' ]]; then
  alias xc='command xsel -i -b'
  alias xp='command xsel -o -b'
fi

# suffix aliases
alias -s crt="command openssl x509 -text -noout -in "
alias -s csr="command openssl req -text -noout -in "
alias -s md="glow"
