#set-option -g prefix C-a
#bind-key C-a send-prefix

set -g set-titles on
# [pane:title] session:host cwd
set -g set-titles-string '[#I:#W] #S:#H #{pane_current_path}'

# truecolor (https://gist.github.com/XVilka/8346728)
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:Tc"

# set -g status-fg green
# set -g status-bg colour233

# set -g status-left-length 30
set -g status-interval 1
# # [session][host]
# set -g status-left '#[dim]#[fg=6][#[fg=7]#S#[fg=6]][#[fg=7]#H#[fg=6]] '
# # [date time]
# set -g status-right ' #[dim]#[fg=6][#[fg=7]%Y-%m-%d %H:%M:%S#[fg=6]]'
# setw -g monitor-activity on
# setw -g window-status-current-style bright
# setw -g window-status-style dim
# setw -g window-status-activity-style none

# catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
# set -g @catppuccin_reset "true"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g status-right-length 100
set -g status-left-length 100
# set -g status-left ""
set -g status-left "#{E:@catppuccin_status_session}"
set -g @catppuccin_date_time_text " %Y-%m-%d %H:%M:%S"
set -gF status-right "#{E:@catppuccin_status_host}"
# set -g status-right "#{E:@catppuccin_status_application}"
# set -agF status-right "#{E:@catppuccin_status_cpu}"
# set -agF status-right "#{E:@catppuccin_status_ram}"
# set -ag status-right "#{E:@catppuccin_status_session}"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -agF status-right "#{E:@catppuccin_status_battery}"
set -agF status-right "#{E:@catppuccin_status_date_time}"
# run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
# run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux


set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 30000

setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
set -g set-clipboard on
set -sg escape-time 10

# wayland
%if "#{==:#{XDG_SESSION_TYPE},wayland}"
  bind-key -T copy-mode-vi 'v' send -X begin-selection
  bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'wl-copy'
  bind -T copy-mode-vi Enter   send -X copy-pipe-and-cancel 'wl-copy'
  bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'wl-copy'
  set -g set-clipboard off
%endif

# x11
%if "#{==:#{XDG_SESSION_TYPE},x11}"
  bind-key -T copy-mode-vi 'v' send -X begin-selection
  bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xsel -i -b'
  bind -T copy-mode-vi Enter   send -X copy-pipe-and-cancel 'xsel -i -b'
  bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'xsel -i -b'
  set -g set-clipboard off
%endif

# byobu lite
source $HOME/.tmux-fkeys.conf
