unbind-key -n F2
unbind-key -n C-F2
unbind-key -n S-F2
unbind-key -n F3
unbind-key -n F4
unbind-key -n F6
unbind-key -n C-F6
unbind-key -n S-F6
unbind-key -n F7
unbind-key -n S-F7
unbind-key -n F8
unbind-key -n F9
unbind-key -n C-F9
unbind-key -n S-F9
unbind-key -n C-F11
unbind-key -n S-F11
unbind-key -n C-F12
unbind-key -n C-Left
unbind-key -n C-Right
unbind-key -n C-S-Left
unbind-key -n C-S-Right
unbind-key -n M-Left
unbind-key -n M-Right
unbind-key -n M-Up
unbind-key -n M-Down
bind-key -n F12 source $HOME/.tmux-fkeys.conf \; display "F-keys: ENABLED"
