# M:ALT C:CTRL S:SHIFT
bind-key -n F2 new-window
bind-key -n C-F2 display-panes \; split-window -h -c "#{pane_current_path}"
bind-key -n S-F2 display-panes \; split-window -v -c "#{pane_current_path}"
bind-key -n F3 previous-window
bind-key -n F4 next-window
bind-key -n F6 detach
bind-key -n C-F6 kill-session
bind-key -n S-F6 confirm-before kill-window
bind-key -n F7 copy-mode
bind-key -n S-F7 set-window-option synchronize-panes \; display "synchronize-panes: #{?pane_synchronized,ENABLED,DISABLED}"
bind-key -n F8 paste-buffer

%if "#{==:#{XDG_SESSION_TYPE},wayland}"
  bind-key -n C-F8 run "tmux set-buffer \"`wl-paste -n`\"; tmux paste-buffer"
%elif "#{==:#{XDG_SESSION_TYPE},x11}"
  bind-key -n C-F8 run "tmux set-buffer \"`xsel -o -b`\"; tmux paste-buffer"
%endif

bind-key -n F9 command-prompt -p "rename-window:" "rename-window '%%'"
bind-key -n C-F9 command-prompt -I "#{session_name}" -p "rename-session:" "rename-session '%%'"
bind-key -n S-F9 command-prompt -I "#{window_name}" -p "rename-window:" "rename-window '%%'"
bind-key -n M-F9 run "tmux.rename-window-git"
bind-key -n C-F11 next-layout
bind-key -n S-F11 resize-pane -Z
bind-key -n F12 source $HOME/.tmux-fkeys-disable.conf \; display "F-keys: DISABLED"

bind-key -n C-Left previous-window
bind-key -n C-Right next-window

bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

bind-key -n M-Left select-pane -L
bind-key -n M-Right select-pane -R
bind-key -n M-Up select-pane -U
bind-key -n M-Down select-pane -D
