# browser shortcuts
Ctrl++ add window-scale 0.08
Ctrl+- add window-scale -0.08

# restore overridden shortcuts
Ctrl+0 add audio-delay 0.100
Ctrl+9 add audio-delay -0.100

# swap these
WHEEL_UP     add volume -2
WHEEL_DOWN   add volume 2
WHEEL_LEFT   seek -10
WHEEL_RIGHT  seek 10
