XDG_CONFIG_HOME="${HOME}/.config"
XDG_CACHE_HOME="${HOME}/.cache"
XDG_CURRENT_DESKTOP=sway

# no menubars 
#QT_QPA_PLATFORM=wayland

QT_QPA_PLATFORM=xcb
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_QPA_PLATFORMTHEME=qt5ct
XCURSOR_SIZE=16

_JAVA_AWT_WM_NONREPARENTING=1

SSH_AUTH_SOCK DEFAULT="${XDG_RUNTIME_DIR}/ssh-agent.socket"
